### ISSUE TITLE
lib/index.js not found?

### ISSUE THREAD

**Issue by AlexSWall** [hyhugh/coc-erlang_ls#4]
After installing this plugin with vim-plug, when entering both vim and nvim I recieve an error message stating
```
[coc.nvim]extension "coc-erlang_ls" doesn't contain main file /Users/Alex/.vim/plug-plugins/coc-erlang_ls/lib/index.js
```
The folder lib doesn't even exist for coc-erlang_ls, am I doing something wrong?

My `~/.vimrc` contains
```
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'hyhugh/coc-erlang_ls', {'do': 'yarn install --frozen-lockfile'}
```
and using `:PlugInstall` gives me the error on loading any subsequent file with vim.

This happens independently of what is in my `:CocConfig`.

**Comment by hyhugh** [comment]
Hi,

As this plugin uses `yarn` to compile the main.js file, do you have `yarn` installed?  
Once you get `yarn` installed, you can go to the plugin's root directory and execute `yarn install --frozen-lockfile` to generate the main.js file. (Vim-plug should have done it for you, if you had yarn installed when installing this plugin)

**Comment by AlexSWall** [comment]
Ah yep, it was the lack of `yarn`! Thanks, a stupid oversight, I'm not familiar with yarn. Probably worth adding after the 'Install' heading in the README that `yarn` needs to be installed in addition to `erlang_ls` (even though it's obvious to some from the vim-plug config line).
